title: "xyz-zyx"
description: "Exploring technology, AI, and possible futures"
baseurl: "/blogxyz"
url: "https://amoha-98.github.io"

header_pages:
  - index.md
  - blog.md
  - projects.md
  - contact.md

style: dark

footer: 'Connect with me on <a href="https://twitter.com/nidarmm">Twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-feed
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

permalink: /:year/:month/:day/:title/
