title: "Portfolio"
description: "Exploring technology, AI, and possible futures"
baseurl: "/blogxyz"
url: "https://amoha-98.github.io"

style: light

footer: 'Connect with me on <a href="https://twitter.com/nidarmmv2">Twitter</a>'

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

permalink: /:year/:month/:day/:title/

# Custom CSS for enhancements
sass:
  style: compressed

